### ISSUE TITLE
I have some questions about latent signal s in KCCA, sorry to bother you

### ISSUE THREAD

**Issue by SoloBean** [steven2358/kmbox#2]
In the km_demo_kcca, you use the latent signal s.  But I can not understand what the meaning of it and how to use it. Sorry to bother you, and would you please teach me about it?

**Comment by steven2358** [comment]
The idea of the demo is that given two different "views" of a signal, this signal can be recovered by applying KCCA. In particular, the two views are different nonlinear transformations of the signal s. "Latent" means that the signal s is present in both views though it is "hidden" underneath the transformations.

In a practical scenario, the signal s could represent the "actions" of a person and the two views could represent the sound and the image (video) associated to the actions. The demo illustrates how to recover a 1D representation of these actions.

**Comment by SoloBean** [comment]
In your explanation, the signal can be recovered from two different "views" of a signal by applying KCCA. But I noticed that you have some data preprocessing like : x1 = [tanh(r1-s)+0.1*r1 r1+3*s-1/10*(sin(3*s))];
What is this meaning and why they can recovered by KCCA. I have read that paper and I am confused about the KCCA. In the process of formula derivation of KCCA, eigenvalues can always be 1 and under constraint conditions, the correlation coefficient is always 1. Does that mean that any two groups of variables can find a non-linear relationship？
Sorry  to bother you again. I am confused a lot and nowhere to find out the answer. I am appreciated that even after such a long time you can answer my questions.

**Comment by steven2358** [comment]
x1 = [tanh(r1-s)+0.1r1 r1+3s-1/10*(sin(3*s))];
This "preprocessing" is actually the nonlinear transformation I was mentioning.

As for the second part of your question, this is discussed in the paper "Kernel Independent Component Analysis", section 3.2.2. If the kernel matrices are invertible then you can always find two nonlinear transformations that produce perfect correlation. This is not desirable and therefore you should regularize.

If you are confused about KCCA then I think it is best you study the papers more in detail. The space here is simply too limited to address the fundamentals of KCCA.
