### ISSUE TITLE
km_kpca return values

### ISSUE THREAD

**Issue by sgmanohar** [steven2358/kmbox#3]
Documentation suggests it should also return the projections Xep. Only two return values though. Could this be implemented? Thanks!

**Comment by steven2358** [comment]
I checked this, The projections are actually the principal components (columns of E) which are already returned. I cleaned up the file.

You can find more details in section 2.2.2 of https://gtas.unican.es/pub/255

**Comment by sgmanohar** [comment]
OK thanks. But "projections" to me means: the data, projected on to the new space - i.e .one row for each row of the original data, and a column for each of the new projected dimensions. Or is that different for nonlinear PCA?

**Comment by steven2358** [comment]
Yes, "projections" means the data, projected onto the new space. You can check the dimensions of E: it's the number of data points times the dimension of new space.

Here's an example: in `km_demo_kpca_u.m`, the data `X` is 120x2: the data are transformed into feature space and then projected onto a space of dimension 4. The projected data `E` are therefore of size 120x4.
